### ISSUE TITLE
Texturepack download hinzufügen

### ISSUE THREAD

**Issue by Lux315** [z0cken/website#5]

**Comment by KingJulian13** [comment]
Wollen / Sollen / Können wir das Ressourcepack auch hier in Github verwalten?

Müsste man mal rechtlich abklären, ob man die veränderten Default Texturen veröffentlichen darf. 

Platzhalter eingefügt mit 282f6e62fea63f4b1a74a3479c99cb8f3f82cbaa

**Comment by KingJulian13** [comment]
Wsl nicht: Musikausschnitte & umgefärbten Originaltexturen sehr kritisch
